#!/usr/bin/env ansible-playbook
---

- hosts: '!g_poweredoff'
  gather_facts: True
  tasks: [ group_by: { key: 'debian_{{ ansible_distribution_release }}' } ]

- hosts: debian_jessie
  gather_facts: False
  become: True

  tasks:

    - copy:
        content: |
          Acquire::Check-Valid-Until no;
        dest: /etc/apt/apt.conf.d/99no-check-valid-until

    - apt_repository:
        repo: '{{ item.repo }}'
        state: '{{ item.state }}'
      vars:
        jessie_updates: 'http://ftp.fr.debian.org/debian/ jessie-updates main'
        jessie-backports: 'http://ftp.fr.debian.org/debian jessie-backports main'
        cran_rstudio: 'https://cran.rstudio.com/bin/linux/debian jessie-cran3/'
        cran_revolutionanalytics: 'http://cran.revolutionanalytics.com/bin/linux/debian jessie-cran3/'
      loop:
        - { state: absent, repo: 'deb {{ jessie_updates }}' }
        - { state: absent, repo: 'deb-src {{ jessie_updates }}' }
        - { state: absent, repo: 'deb {{ jessie-backports }}' }
        - { state: absent, repo: 'deb {{ cran_rstudio }}' }
        - { state: absent, repo: 'deb-src {{ cran_rstudio }}' }
        - { state: absent, repo: 'deb cran_revolutionanalytics' }
        - { state: absent, repo: 'deb-src cran_revolutionanalytics' }

        - { state: present, repo: 'deb http://archive.debian.org/debian jessie-backports main' }
