#!/usr/bin/env ansible-playbook
---

- hosts: 'n_admin2:!g_poweredoff:!g_impact'
  gather_facts: True
  tasks: [ group_by: { key: 'debian_{{ ansible_distribution_release }}' } ]

- hosts: debian_jessie:debian_stretch
  gather_facts: False
  become: True

  tasks: [ apt: { name: jq } ]
