---

# ansible-galaxy install -r requirements.yml

- src: git@thyepi.github.com:Epiconcept-Paris/infra-legacy-ar-named.git
  scm: git
  version: master
  accept_hostkey: True
  key_file: ~/.ssh/id_epiconcept
  name: legacy-named

- src: git@github.com:thydel/ar-hg-etc-com.git
  scm: git
  name: hg-etc-com
  version: use-module

- src: git@github.com:thydel/ar-automysqlbackup.git
  scm: git
  name: automysqlbackup
  version: master
